### PR TITLE
Fix consts for finite field arithemtic

### PR DESCRIPTION
**Pull request by emilbayes**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

**Comment by emilbayes** [comment]
Just reading through the docs :) Exciting stuff

**Comment by jedisct1** [comment]
These are also implemented in [wasm-crypto](https://github.com/jedisct1/wasm-crypto).

**Comment by emilbayes** [comment]
Dang, what's left for me to do then? Good work! :)

**Pull request merged**
