### PR TITLE
Request adding my project PipeSocks to the libsodium project list

### PR DESCRIPTION
**Pull request by yvbbrjdr**
- [PipeSocks](https://github.com/yvbbrjdr/pipesocks): A pipe-like SOCKS5 tunnel system.

### CODE REVIEW

**Comment by jedisct1** [comment]
Merged, thanks!

**Comment by yvbbrjdr** [comment]
Thanks

**Comment by jedisct1** [comment]
Nice project! I'll give it a try.

**Comment by yvbbrjdr** [comment]
Umm... In fact, I wrote this project for me to go through the Great Fire Wall in China. You guys might use this for anonymous?

**Comment by yvbbrjdr** [comment]
Actually I am wondering are there gonna be other strong encryption algorithms in libsodium, such as NTRU, to make it harder to break?

**Comment by jedisct1** [comment]
None of the current algorithms in the library can be broken nonw, even by nation-state adversaries.

Post-quantum algorithms will eventually be added, but GFW filters are likely to keep blocking VPN-like apps based on protocol specificities rather than "breaking" encrypted payloads.

**Comment by yvbbrjdr** [comment]
I think the process of public key exchange might recognized and blocked. How do I avoid it?

**Pull request merged**
