### PR TITLE
Spelling/grammar fixes part 4

### PR DESCRIPTION
**Pull request by samuel-lucas6**
There are a few things that might be worth changing:
- The scrypt page now uses MiB/GiB, except for ~127 GB, because that's what was used on the Argon2 page. Perhaps it should be MB/GB.
- Is 'What will be the highest number of threads/processes evaluating the function simultaneously (ideally, no more than 1 per CPU core)?' on the [Argon2](https://doc.libsodium.org/password_hashing/default_phf#guidelines-for-choosing-the-parameters) page necessary since parallelism can't be adjusted?
- Should the scrypt being more conservative than Argon2 claim now be removed?

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks again for this new batch of updates, Samuel!

The flip side of using a CPU hard function is that it can immediately render an application vulnerable to trivial DoS attacks. 

When used for authentication, N users trying to log in simultaneously are going to require at least N CPU cores in order to complete the computation in the expected time. As soon as the bar is reached, interactive logins may not be interactive any longer, or CPU cores designed to run the actual application will have to be repurposed for key derivation. And a waiting queue to log in would obviously be unacceptable.

Using multiple thread for a single key derivation is nice if the expectation is that only one user is authenticating at a time. However,  I don't think this is a common use case, especially with interactive settings. 

So, this is what "the highest number of threads/processes evaluating the function simultaneously" refers to.

**Comment by jedisct1** [comment]
> Should the scrypt being more conservative than Argon2 claim now be removed?

Yep, Argon2 is quite mature at this point.

**Comment by samuel-lucas6** [comment]
> Using multiple thread for a single key derivation is nice if the expectation is that only one user is authenticating at a time. However, I don't think this is a common use case, especially with interactive settings.
> 
> So, this is what "the highest number of threads/processes evaluating the function simultaneously" refers to.

Thank you for that explanation.

> Yep, Argon2 is quite mature at this point.

Cool, I've rephrased that now.

**Comment by jedisct1** [comment]
Thank you Samuel!

**Pull request merged**
