### PR TITLE
bindings_for_other_languages: List unmaintained.

### PR DESCRIPTION
**Pull request by samuel-lucas6**
@ektrah mentioned cleaning up the .NET bindings in terms of providing guidance on which ones to use, but I noticed that a lot of the bindings appear to be unmaintained, so I've attempted to classify them. My criteria was whether the library has had any commits in the last year or two and whether the owner has done commits on their account in the last few months in more ambiguous cases.

Some are very clearly unmaintained (e.g. archived, a notice, no response to issues/PRs for years), so at the very least, I think it would be beneficial to have a note in those cases.

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks a lot!

Sometimes, projects move to a different repository/organization. But it's hard to see track of everything.

We should probably just remove unmaintained entries from the list.

**Comment by samuel-lucas6** [comment]
> We should probably just remove unmaintained entries from the list.

Sounds good to me. Is there a specific criteria you'd like me to follow? I don't want to accidentally remove libraries that are being maintained version wise (supporting 1.0.18) but haven't had recent commits. For example, I could remove everything below 1.0.18 and any archived, with a notice, etc. I could also create an issue in some and see if I get a quick reply.

**Comment by jedisct1** [comment]
Creating an issue and see what maintainers respond (if they do) may be the best way to go.

**Comment by samuel-lucas6** [comment]
I'm sorry if this filled up your inbox Frank. Hopefully it will make things easier to track. I'll edit this comment when I hear back from people.

Archived:
- libsalty
- libstodium
- kalium
- ocaml-sodium
- Pharo/Squeak: Crypto-NaCl (believe I read this was no longer maintained in another repo)
- NaOH

Still/going to be maintained after contact:
- erlang-libsodium (in the future)
- sodium-wrapper (in the future)

Confirmed unmaintained after contact:
- libsodium-net
- libsodium-core
- fortium
- datkt / sodium
- php-sodium

**Comment by jedisct1** [comment]
Thank a ton for that hard work, Samuel, this is fantastic, and very useful for people looking for up-to-date, maintained bindings. Also good to see that some maintainers may update their code after your message :)

We can make the changes to the documentation now, and re-add projects later if you get a response from their maintainer.

**Comment by samuel-lucas6** [comment]
Just to check, does this look ok to merge @jedisct1? Haven't had any replies recently.

**Pull request merged**
