### PR TITLE
Update projects using libsodium

### PR DESCRIPTION
**Pull request by bschick**
Added https://quickcrypt.org

### CODE REVIEW

**Comment by jedisct1** [comment]
Oh, this is a cool project!

Good job!

**Comment by jedisct1** [comment]
Love the fact that the protocol is sound and nicely documented!

Someone reported that it doesn't work well on mobile in portrait mode, though.

**Comment by bschick** [comment]
I can take a look. Where is did you get that report?

**Comment by jedisct1** [comment]
> I can take a look. Where is did you get that report? I wonder if its a layout problem or passkeys. I find passkey to be rather flaky on both iOS and Android.

Twitter, after I talked about it. There was a screenshot of the documentation as an example, so it looks like a layout problem.

**Comment by bschick** [comment]
Thanks for the heads up. I made a number of layout fixes for small-screens
(mobile) browsers. Tested on iOS and Android.

**Pull request merged**
