### PR TITLE
clarify that it is more than just integrity

### PR DESCRIPTION
**Pull request by simbo1905**

### CODE REVIEW

**Comment by jedisct1** [comment]
That wouldn't be correct, unless the ciphertext is signed.

This whole page is confusing and really needs a rewrite.

**Comment by simbo1905** [comment]
Signing the cypher text is what I thought it was talking about. Can you confirm that this library supports that?

**Comment by jedisct1** [comment]
It supports authenticated encryption and signatures, so you can compose them.

**Comment by simbo1905** [comment]
Great. We will sign our cypher text so that we can confirm the source of the message.

**Comment by jedisct1** [comment]
If possible, sign first, then encrypt.

**Pull request closed without merging**
